---
- name: Stop Monad services
  ansible.builtin.systemd:
    name: "monad{{ type_suffix }}-{{ item }}.service"
    state: stopped
  loop:
    - consensus
    - execution
    - rpc
  vars:
    type_suffix: "{{ '' if type == 'validator' else '-' + type }}"

- name: Create page migration directory
  ansible.builtin.file:
    path: "{{ consensus_home_dir }}/page-migration"
    state: directory
    owner: "{{ service_identifier }}"
    group: "{{ project }}"
    mode: "0755"

- name: Deactivate secondary triedb partition
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_mpt.dest_binary_name }} \
      --storage {{ triedb_config.path }} \
      --deactivate-secondary || true
  args:
    executable: /bin/bash
  register: mpt_partition_deactivate
  changed_when: mpt_partition_deactivate.rc == 0
  failed_when: mpt_partition_deactivate.rc != 0
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Repair triedb partition
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_mpt.dest_binary_name }} \
      --storage {{ triedb_config.path }} \
      --repair
  args:
    executable: /bin/bash
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Activate secondary triedb partition
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_mpt.dest_binary_name }} \
      --storage {{ triedb_config.path }} \
      --activate-secondary \
      --state-machine monad
  args:
    executable: /bin/bash
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Dump binary snapshot
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_cli.dest_binary_name }} \
      --db {{ triedb_config.path }} \
      --version latest_finalized \
      --dump-binary-snapshot {{ consensus_home_dir }}/page-migration
  args:
    executable: /bin/bash
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Load binary snapshot
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_cli.dest_binary_name }} \
      --db {{ triedb_config.path }} \
      --version latest_finalized \
      --load-binary-snapshot {{ consensus_home_dir }}/page-migration \
      --secondary
  args:
    executable: /bin/bash
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Check storage status
  ansible.builtin.shell: |
    ulimit -n 65536
    {{ consensus_bin_dir }}/{{ consensus_binaries.monad_mpt.dest_binary_name }} \
      --storage {{ triedb_config.path }}
  args:
    executable: /bin/bash
  register: mpt_storage_status
  environment:
    LD_LIBRARY_PATH: "{{ consensus_lib_dir }}"

- name: Display monad-mpt storage status
  ansible.builtin.debug:
    msg: "{{ mpt_storage_status.stdout }}"

- name: Confirm page migration details
  ansible.builtin.pause:
    seconds: 40

- name: Restart Monad services
  ansible.builtin.systemd:
    name: "monad{{ type_suffix }}-{{ item }}.service"
    state: restarted
  loop:
    - consensus
    - execution
    - rpc
  vars:
    type_suffix: "{{ '' if type == 'validator' else '-' + type }}"
