---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    monad:
      hosts:
        consensus.monad.testnet.encapsulate.xyz:
          type: consensus
        execution.monad.testnet.encapsulate.xyz:
          type: execution
          ledger_dir: /opt/monad-consensus/data
          socket_dir: /opt/monad-consensus/socket
        rpc.monad.testnet.encapsulate.xyz5:
          type: rpc
          socket_dir: /opt/monad-consensus/socket
