---
# maintains testnet inventory grouped by project names
all:
  vars:
    env: testnet
  children:
    monad:
      hosts:
        validator.monad.testnet.encapsulate.xyz:
          type: validator
          consensus_home_dir: /opt/monad-consensus
          ledger_dir: /opt/monad-consensus/data
          socket_dir: /opt/monad-consensus/socket
