---
- name: Create a tmp directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Download and unarchive the binary
  vars:
    suffix_url: "v{{ monad[type].mev.version }}/{{ mev_service_default_binary_name }}_{{ monad[type].mev.version }}_{{ system_architecture }}.deb"
  ansible.builtin.get_url:
    url: "{{ monad[type].mev.source_url }}/{{ suffix_url }}"
    dest: "{{ tmp_dir }}/{{ service_identifier }}"
    owner: root
    group: root
    mode: "0755"

- name: Extract binary package
  ansible.builtin.command:
    cmd: >-
      dpkg-deb -x
      "{{ tmp_dir }}/{{ service_identifier }}/{{ mev_service_default_binary_name }}_{{ monad[type].mev.version }}_{{ system_architecture }}.deb"
      {{ tmp_dir }}/{{ service_identifier }}
    creates: "{{ tmp_dir }}/{{ service_identifier }}/usr"

- name: Copy the binary file
  ansible.builtin.copy:
    src: "{{ tmp_dir }}/{{ service_identifier }}/usr/bin/{{ mev_service_default_binary_name }}"
    dest: "{{ mev_bin_dir }}/{{ service_identifier }}"
    remote_src: true
    owner: root
    group: root
    force: true
    mode: "0755"
  notify:
    - Restart service

- name: Clean up the temporary directory
  ansible.builtin.file:
    path: "{{ tmp_dir }}/{{ service_identifier }}"
    state: absent
